name: Testar Aplicação Node.js

on:
  push:
    branches:
      - main

jobs:
  test-app:
    runs-on: ubuntu-latest
    container: node:16

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2
    
    - name: Listar Conteúdo do Diretório
      run: ls
    
    - name: Mover para o diretório da API
      run: cd api
   
    - name: Depurar
      run: pwd && ls
    
    - name: Instalar dependências
      run: npm install

    - name: Iniciar a aplicação
      run: npm start &

    - name: Esperar pela inicialização da aplicação
      run: sleep 10

    - name: Rodar testes
      run: |
        curl -X GET http://localhost:3001/listaAtividade

    - name: Parar a aplicação
      run: kill $(pgrep node)
